server:
  servlet:
    context-path: /KeSystem
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/manager_system?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*Mapping.xml
  type-aliases-package: com.example.demo.user.entity

#showSql
logging:
  level:
    com:
      example:
          demo: info